# Generated by Django 4.2.3 on 2023-07-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiters', '0003_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Count',
        ),
        migrations.AddField(
            model_name='visiter',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
